### ISSUE TITLE
finish calling script

### ISSUE THREAD

**Issue by stedmanblake** [stedmanblake/chativism#6]
- [ ] remove the border, padding, quote icon
- [ ] finalize the copy

**Comment by stedmanblake** [comment]
@barneyjackson should this be Issue-specific? I'm thinking not for now, though it's worth thinking about it, what it'd look like, or whether there are other things we could surface for them, like a list of bullet points, for and against.

**Comment by barneyjackson** [comment]
I would say no, and definitely not yet, just because of the content creation overhead involved

On 26 Dec 2016 21:37, Stedman Blake Hood <notifications@github.com> wrote:

@barneyjackson<https://github.com/barneyjackson> should this be Issue-specific? I'm thinking not for now, though it's worth thinking about it, what it'd look like, or whether there are other things we could surface for them, like a list of bullet points, for and against.
